#!/bin/sh

echo "[+] Taking snapshot of running proccesses"
ps -w | sed 's/\[/\\[/' | sed 's/\]/\\]/' | grep -v sed | cut -c 27- | sed 's/(/\\(/' | sed 's/)/\\)/' | sed 's/{/\\{/' | sed 's/}/\\}/' | sed 's/^/^/' | sed 's/$/$/' > monitor_file.base

#Add extra proccesses not to be monitored
echo "monitor" >> monitor_file.base
echo "grep" >> monitor_file.base
echo "ps" >> monitor_file.base
echo "bash" >> monitor_file.base
echo "sed" >> monitor_file.base
echo "kworker" >> monitor_file.base

for i in 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1
do
	echo "[+] Building baseline please wait $i seconds"	
	ps -w | egrep -vf monitor_file.base
	ps -w | egrep -vf monitor_file.base | sed 's/\[/\\[/' | sed 's/\]/\\]/' | cut -c 27- | sed 's/(/\\(/' | sed 's/)/\\)/' | sed 's/{/\\{/' | sed 's/}/\\}/' | sed 's/^/^/' | sed 's/$/$/' >> monitor_file.base
	sleep 1
done
echo "[+] Baseline complete"

echo "[+] Proccess monitor has started!"

while true; do 

ps -w | egrep -vf monitor_file.base
done 
